export const ADD_TOTO = 'add_toto'
export const DELETE_TODO = 'delete_todo'
export const SELECT_ALL = 'select_all'
export const CLEAR_ALL_COMPLETED = 'clear_all_completed'
export const RECEIVE_TODOS = 'receive_todos'